import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import { CurrentUserProvider } from '@/context/CurrentUser'
import { OrgConfigProvider } from '@/context/OrgConfig'

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Kijaide",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${manrope.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col font-sans bg-slate-100 text-slate-900">
        <OrgConfigProvider>
          <CurrentUserProvider>{children}</CurrentUserProvider>
        </OrgConfigProvider>
      </body>
    </html>
  );
}
